#!/usr/bin/env sh
set -eu
WP_SKIP_UPDATE_CHECK=1 wp audit secrets-policy
WP_SKIP_UPDATE_CHECK=1 wp audit absolute-path-policy --root .
WP_SKIP_UPDATE_CHECK=1 wp audit secrets-config
WP_SKIP_UPDATE_CHECK=1 wp audit secret-provider-quarantine
WP_SKIP_UPDATE_CHECK=1 wp audit no-dev-vars
